# Generated by Django 6.0.8 on 2026-09-30 09:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_spin_snapshots(apps, schema_editor):
    Spin = apps.get_model("wheel", "Spin")
    for spin_record in Spin.objects.select_related("prize").iterator():
        spin_record.request_id = uuid.uuid4()
        spin_record.prize_slot = spin_record.prize.slot
        spin_record.prize_name = spin_record.prize.name
        spin_record.prize_description = spin_record.prize.description
        spin_record.prize_icon = spin_record.prize.icon
        spin_record.prize_color = spin_record.prize.color
        spin_record.save(
            update_fields=[
                "prize_slot",
                "prize_name",
                "prize_description",
                "prize_icon",
                "prize_color",
                "request_id",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'Coupon', 'verbose_name_plural': 'Coupons'},
        ),
        migrations.AlterModelOptions(
            name='prize',
            options={'ordering': ['slot'], 'verbose_name': 'Prize', 'verbose_name_plural': 'Prizes'},
        ),
        migrations.AlterModelOptions(
            name='spin',
            options={'ordering': ['-created_at'], 'verbose_name': 'Spin', 'verbose_name_plural': 'Spin history'},
        ),
        migrations.AddField(
            model_name='spin',
            name='prize_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Prize color snapshot'),
        ),
        migrations.AddField(
            model_name='spin',
            name='prize_description',
            field=models.CharField(blank=True, max_length=180, verbose_name='Prize description snapshot'),
        ),
        migrations.AddField(
            model_name='spin',
            name='prize_icon',
            field=models.CharField(blank=True, max_length=8, verbose_name='Prize icon snapshot'),
        ),
        migrations.AddField(
            model_name='spin',
            name='prize_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Prize name snapshot'),
        ),
        migrations.AddField(
            model_name='spin',
            name='prize_slot',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Prize slot'),
        ),
        migrations.AddField(
            model_name='spin',
            name='request_id',
            field=models.UUIDField(editable=False, null=True, verbose_name='Request identifier'),
        ),
        migrations.RunPython(backfill_spin_snapshots, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='spin',
            name='request_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Request identifier'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='prize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='wheel.prize', verbose_name='Preassigned prize'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='redeemed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Redeemed at'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='color',
            field=models.CharField(default='#7C3AED', max_length=7, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='description',
            field=models.CharField(blank=True, max_length=180, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='icon',
            field=models.CharField(default='🎁', max_length=8, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive prizes remain on the wheel and are still honored for issued coupons.', verbose_name='Available for new coupons'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Prize name'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='slot',
            field=models.PositiveSmallIntegerField(help_text='A number from 0 through 11; slot 0 is at the top.', unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='Wheel slot'),
        ),
        migrations.AlterField(
            model_name='spin',
            name='coupon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='spin', to='wheel.coupon', verbose_name='Coupon'),
        ),
        migrations.AlterField(
            model_name='spin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Spun at'),
        ),
        migrations.AlterField(
            model_name='spin',
            name='prize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spins', to='wheel.prize', verbose_name='Prize'),
        ),
        migrations.AlterField(
            model_name='spin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddConstraint(
            model_name='spin',
            constraint=models.UniqueConstraint(fields=('user', 'request_id'), name='unique_spin_request_per_user'),
        ),
    ]
